### ISSUE TITLE
android 9.0播放音乐闪退

### ISSUE THREAD

**Issue by Jay-huangjie** [neugaojin/SEMusic#8]
报错日志
````
2019-04-13 11:11:06.293 8087-8087/com.se.music E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.se.music, PID: 8087
    java.lang.SecurityException: Permission Denial: startForeground from pid=6369, uid=10306 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at com.se.music.IMediaAidlInterface$Stub$Proxy.play(IMediaAidlInterface.java:404)
        at com.se.music.service.MusicPlayer$Companion.playAll(MusicPlayer.kt:105)
        at com.se.music.adapter.MusicListAdapter$PlayMusic.run(MusicListAdapter.kt:59)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
````
建议楼主适配一下前台服务：
启动service使用`startForegroundService`函数启动，在`AndroidManifest`中添加权限
````
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
````

**Comment by neugaojin** [comment]
ok  多谢，还有一个是网络请求的问题，我会在一起改一下，最近工作有点忙，一直没来得及改
